apiVersion: apps/v1
kind: Deployment
metadata:
  name: StockManagement
  labels:
    app: StockManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: StockManagement
  template:
    metadata:
      labels:
        app: StockManagement
    spec:
      containers:
        - name: StockManagement
          image: username/StockManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5